export default {
    PRIMARY_COLOR: '#2AABB8',
    FONT_SIZE_SMALL: 12,
    FONT_SIZE_MEDIUM: 14,
    FONT_SIZE_LARGE: 16,
    FONT_WEIGHT_LIGHT: '200',
    FONT_WEIGHT_MEDIUM: '500',
    FONT_WEIGHT_BOLD: '700',
    BACKGROUND_COLOR_LIGHT: '#F0F6F7',
    CONTAINER_PADDING: 20,
    TEXT_INPUT_PADDING: 10
};